apiVersion: issue.natssecrets.crossplane.io/v1alpha1
kind: Operator
metadata:
  name: myoperator
spec:
  forProvider:
    syncAccountServer: true
    claims:
      operator:
        systemAccount: sys
        accountServerUrl: "nats://nats.nats:4222"
        operatorServiceUrls:
          - nats://nats.nats:4222
        signingKeys:
          - opsk1
        strictSigningKeyUsage: false
  providerConfigRef:
    name: vault-creds
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: myoperator
