apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-natssecrets
  annotations:
    meta.crossplane.io/maintainer: Crossplane Maintainers <info@crossplane.io>
    meta.crossplane.io/source: github.com/edgefarm/provider-natssecrets
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      A Crossplane provider for managing EdgeFarm's Vault NATS secrets plugin.
      https://github.com/edgefarm/vault-plugin-secrets-nats

spec:
  controller:
    image: ghcr.io/edgefarm/provider-natssecrets/provider-natssecrets-controller:VERSION
